### PR TITLE
Give more context for pending/failed steps with progress formatter

### LINKED ISSUE #688: Improve progress formatter output to show more information about failure, similar to 2.x
In 2.x progress formatter output was very descriptive for failure:
1. Had failure number
2. Failing step
3. Failing scenario with path
4. Feature in which failure happened.
```
01. Xpath matching locator "//li[@id='section-2']/descendant::div[@class='section-modchooser']/span/a" not found.
  In step `And I add a "Page" to section "2"'. # behat_course::i_add_to_section()
    From scenario `Test condition'.              # /home/rajesh/behat/availability_profile.feature:25
    Of feature `availability_profile'.
```
But in 3.x output is limited to:
1. Failing step with path
2. Exception.
```
Then I should see "You are logged in as Admin User" in the "page-footer" "region1" # /home/rajesh/behat/availability_profile.feature:25
      The "region1" selector type does not exist (Behat\Mink\Exception\ExpectationException)
```
It would be nice to have a failure information similar to 2.x

### PR DESCRIPTION
**Pull request by everzet**
Change in scenario:

```diff
-          Then I should have 5 apples # features/apples.feature:11
-            Failed asserting that 2 matches expected 5.
+          002 Scenario: I'm little hungry   # features/apples.feature:9
+                Then I should have 5 apples # features/apples.feature:11
+                  Failed asserting that 2 matches expected 5.
```

Change in outline example:

```diff
-          Then I should have 4 apples # features/apples.feature:20
-            Failed asserting that 3 matches expected 4.
+          001 Example: | 2   | 2     | 4      | # features/apples.feature:26
+                Then I should have 4 apples     # features/apples.feature:20
+                  Failed asserting that 3 matches expected 4.
```

Closes #688

### CODE REVIEW

File: src/Behat/Behat/Output/Node/Printer/ListPrinter.php [hunk 1]
```diff
@@ -154,6 +149,8 @@ public function printFailedHooksList(OutputPrinter $printer, $intro, array $fail
      * @param string        $style
      * @param null|string   $stdOut
      * @param null|string   $error
+     *
+     * @deprecated Remove in 4.0
```
Comment (Taluu) [inline src/Behat/Behat/Output/Node/Printer/ListPrinter.php]: why keep this private method ? It's private so you can safely remove it imo

Comment (everzet) [inline src/Behat/Behat/Output/Node/Printer/ListPrinter.php]: I can not remove the method, because it is a dependency of the other deprecated logic. It's more of a reminder for myself to drop the guy in 4.0.
