### PR TITLE
Catch PHP7 errors implementing Throwable

### LINKED ISSUE #831: Catch  `\Throwable` in PHP 7 so that fatal errors do not halt test execution (how?)
I would like to contribute a patch for this, but I have a few questions before I can do that.

Now PHP 7 is out, fatal errors no longer need to halt test execution. It looks like appropriate place in  `makeCall` method in  in the [`CallCenter`](https://github.com/Behat/Behat/blob/718159921b1d844b8805b5ab2e7d1be34ca323cb/src/Behat/Testwork/Call/CallCenter.php) class

```php
public function makeCall(Call $call)
{
    try {
        $filteredCall = $this->filterCall($call);
        $result = $this->handleCall($filteredCall);
        $filteredResult = $this->filterResult($result);
    } catch (Exception $e) {
        return new CallResult($call, null, $e, null);
    } catch (\Throwable $e) {
        // Cast \Throwable to \Exception?
        $e = throwableToException($e);
        return new CallResult($call, null, $e, null);
    }

    return $filteredResult;
}
```

I have something along these lines working however I am not sure how to handle the cast of `Throwable` to `Exception` in the context of Behat.  Symfony handles it via [ `FatalThrowableException`](https://github.com/symfony/symfony/blob/a729462ce1405497b9bec285d2e83f6e60b987d5/src/Symfony/Component/Debug/Exception/FatalThrowableError.php) but to be frank I don't fully understand the constructor of that class, why is `ErrorException` instantiated but not assigned for example?

I would appreciate any pointers to getting a PR open (or a PR would be great too)

### PR DESCRIPTION
**Pull request by peterjmit**
Resolves #831 

Questions:

- ~~How to correctly handle the version differences? JUnit formatter/feature might be problematic~~ 
- `FatalThrowableError` has been re-appropriated from Symfony, do I need to include licensing?

### CODE REVIEW

File: src/Behat/Testwork/Exception/FatalThrowableError.php [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+ */
+
+namespace Behat\Testwork\Exception;
+
+use ErrorException;
+use ParseError;
+use Throwable;
+use TypeError;
+
+class FatalThrowableError extends ErrorException
```
Comment (stof) [inline src/Behat/Testwork/Exception/FatalThrowableError.php]: Please keep the ``@author`` annotation with the original author (i.e. @nicolas-grekas IIRC)

File: src/Behat/Testwork/Exception/FatalThrowableError.php [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+
+/*
+ * This file is part of the Behat Testwork.
+ * (c) Konstantin Kudryashov <ever.zet@gmail.com>
+ *
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+namespace Behat\Testwork\Exception;
```
Comment (stof) [inline src/Behat/Testwork/Exception/FatalThrowableError.php]: This exception should be in ``Behat\Testwork\Call\Exception``, as it is only used by the Call subsystem

File: features/junit_format.feature [hunk 3]
```diff
@@ -538,6 +538,7 @@
       """
     And the file "junit/default.xml" should be a valid document according to "junit.xsd"
 
+  @php-version @php5.3 @php5.4 @php5.5 @php5.6
```
Comment (stof) [inline features/junit_format.feature]: PHP 5.6 already runs the scenario tagged as ``@php5.4``, due to the way our Travis config works. It is meant to be a min version (and the code used in the Travis setup is currently broken for PHP 7+ when generating the list btw)

File: features/junit_format.feature [hunk 4]
```diff
@@ -538,6 +538,7 @@
       """
     And the file "junit/default.xml" should be a valid document according to "junit.xsd"
 
+  @php-version @php5.3 @php5.4
```
Comment (peterjmit) [inline features/junit_format.feature]: @stof not sure if this is what you meant, perhaps just `php5.3` if it works as a "minimum version"

Comment (stof) [inline features/junit_format.feature]: no need to put anything there, as 5.3 is the min version supported by Behat instead. And using it to exclude PHP 7 is wrong though. It has this behavior only because the code used on Travis actually treats PHP 7.0 as a 5.0 release (so excluding any test with a min version tag)

Comment (peterjmit) [inline features/junit_format.feature]: @stof this test fails on php 7 locally (imo is expected to fail), so do I remove the tags or not?

File: src/Behat/Testwork/Call/Exception/FatalThrowableError.php [hunk 5]
```diff
@@ -0,0 +1,55 @@
...
+
+        parent::__construct(
+            $message,
+            $e->getCode(),
+            $severity,
+            $e->getFile(),
+            $e->getLine()
+        );
+
+        $this->setTrace($e->getTrace());
```
Comment (Taluu) [inline src/Behat/Testwork/Call/Exception/FatalThrowableError.php]: why do you set the trace here like this, when just using the `Throwable` exception as a previous exception (last parameter of every Exception object or almost, including `ErrorException`) should do the trick ?

Comment (Taluu) [inline src/Behat/Testwork/Call/Exception/FatalThrowableError.php]: In @nicolas-grekas's implementation, it had sense because he is making his own stack trace, while here you just forcefully set the trace to be the one of the `Throwable`

Comment (stof) [inline src/Behat/Testwork/Call/Exception/FatalThrowableError.php]: @Taluu The goal is to make the FatalThrowableError appear as being the original error instead of seeing a FatalThrowableError traced in CallCenter and then having to investigate linked exceptions

**Comment by peterjmit** [comment]
@stof @everzet  Scrutinizer timed out and I don't have access to restart, can one of you do the honors?

**Comment by kamazee** [comment]
@peterjmit you can simply amend a commit with nothing (just to change its hash) and push (with force), it should restart builds.

**Comment by peterjmit** [comment]
This should be ready to merge unless there is more feedback/changes required for the PHP7 tag on the `junit` feature
