### PR TITLE
Provide clearer exception message when long token names used

### LINKED ISSUE #872: Warning: preg_match(): Compilation failed: subpattern name is too long
There is my .feature file:

```
Feature: Education Calculator
    As a customer
    In order to count how much money to save in a period of time to get my kids the best education

    Scenario: Count how much to save
        Given My child age now is 7 years old
        And My child age when she/he will using the money is 19 years old
        And He/she will use the money for 12 years
        And I need totally 600000000 for his/him education
        And My saving for his/him education is 25000000
        And My monthly saving for his/him education is 0
        And the annual interest rate is 6%
        And the inflation rate per year is 4%
        When I calculate
        Then I should get 960619331 as my totally need (after adjusted with inflation)
        And I should get 40025805 as the Future Value of my current saving
        And I should get 0 as the Future Value of my educational monthly savings
        And I should get 40025805 as my total saving when the education start
        And I should get 920593526 more money to save
        And I should save more 5014346 monthly
        And I should save more 60172155 yearly
```

But when i run `behat` it gave me PHP warning:

```
PHP Warning:  preg_match(): Compilation failed: subpattern name is too long (maximum 32 characters) at offset 56 in /home/baboon/.composer/vendor/behat/behat/src/Behat/Behat/Definition/Search/RepositorySearchEngine.php on line 120
```

Is any one got similar problem? Or whats wrong with my feature file?

### PR DESCRIPTION
**Pull request by everzet**
TurnipPatternPolicy defines the transformation of turnip notation into a
regular expression using named captures.

PHP forbids usage of capture names longer than 32 symbols. That was
generating cryptic error message. This commit provides clearer
exception.

Closes #872

### CODE REVIEW

File: src/Behat/Behat/Definition/Pattern/Policy/TurnipPatternPolicy.php [hunk 1]
```diff
@@ -132,11 +133,22 @@ private function replaceTokensWithRegexCaptureGroups($regex)
...
             self::PLACEHOLDER_REGEXP,
-            function ($match) use ($tokenRegex) { return sprintf($tokenRegex, $match[1]); },
+            array($this, 'replaceTokenWithRegexCaptureGroup'),
             $regex
         );
     }
 
+    private function replaceTokenWithRegexCaptureGroup($tokenMatch)
+    {
+        if (mb_strlen($tokenMatch[1]) >= 32) {
```
Comment (stof) [inline src/Behat/Behat/Definition/Pattern/Policy/TurnipPatternPolicy.php]: does PHP really allows for multibyte chars in capture group names, and handles them properly ? I don't think so. I'm quite sure the limit is 32 single-byte chars. So you should use ``strlen``

**Comment by everzet** [comment]
Good one. Will fix this evening.
