### PR TITLE
Use key

### LINKED ISSUE #1151: Undefined index with question helper
Getting this stack trace:

```
In QuestionHelper.php line 53:
                                                             
  [Symfony\Component\Debug\Exception\ContextErrorException]  
  Notice: Undefined index: App\Features\ApiContext           
                                                             

Exception trace:
 Symfony\Component\Console\Helper\QuestionHelper->ask() at /app/vendor/behat/behat/src/Behat/Behat/Context/Cli/InteractiveContextIdentifier.php:95
 Behat\Behat\Context\Cli\InteractiveContextIdentifier->askQuestion() at /app/vendor/behat/behat/src/Behat/Behat/Context/Cli/InteractiveContextIdentifier.php:75
 Behat\Behat\Context\Cli\InteractiveContextIdentifier->guessTargetContextClass() at /app/vendor/behat/behat/src/Behat/Behat/Context/Snippet/Generator/AggregateContextIdentifier.php:47
 Behat\Behat\Context\Snippet\Generator\AggregateContextIdentifier->guessTargetContextClass() at /app/vendor/behat/behat/src/Behat/Behat/Context/Snippet/Generator/CachedContextIdentifier.php:52
 Behat\Behat\Context\Snippet\Generator\CachedContextIdentifier->guessTargetContextClass() at /app/vendor/behat/behat/src/Behat/Behat/Context/Snippet/Generator/ContextSnippetGenerator.php:106
 Behat\Behat\Context\Snippet\Generator\ContextSnippetGenerator->supportsEnvironmentAndStep() at /app/vendor/behat/behat/src/Behat/Behat/Snippet/SnippetRegistry.php:136
 Behat\Behat\Snippet\SnippetRegistry->generateSnippet() at /app/vendor/behat/behat/src/Behat/Behat/Snippet/SnippetRegistry.php:101
 Behat\Behat\Snippet\SnippetRegistry->generateSnippets() at /app/vendor/behat/behat/src/Behat/Behat/Snippet/SnippetRegistry.php:85
 Behat\Behat\Snippet\SnippetRegistry->getUndefinedSteps() at /app/vendor/behat/behat/src/Behat/Behat/Snippet/Cli/SnippetsController.php:158
 Behat\Behat\Snippet\Cli\SnippetsController->printUndefinedSteps() at /app/vendor/symfony/event-dispatcher/EventDispatcher.php:212
 Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() at /app/vendor/behat/behat/src/Behat/Testwork/EventDispatcher/TestworkEventDispatcher.php:39
 Behat\Testwork\EventDispatcher\TestworkEventDispatcher->dispatch() at /app/vendor/behat/behat/src/Behat/Testwork/EventDispatcher/Tester/EventDispatchingExercise.php:84
 Behat\Testwork\EventDispatcher\Tester\EventDispatchingExercise->tearDown() at /app/vendor/behat/behat/src/Behat/Testwork/Ordering/OrderedExercise.php:94
 Behat\Testwork\Ordering\OrderedExercise->tearDown() at /app/vendor/behat/behat/src/Behat/Testwork/Tester/Cli/ExerciseController.php:150
 Behat\Testwork\Tester\Cli\ExerciseController->testSpecifications() at /app/vendor/behat/behat/src/Behat/Testwork/Tester/Cli/ExerciseController.php:108
 Behat\Testwork\Tester\Cli\ExerciseController->execute() at /app/vendor/behat/behat/src/Behat/Testwork/Cli/Command.php:63
 Behat\Testwork\Cli\Command->execute() at /app/vendor/symfony/console/Command/Command.php:252
 Symfony\Component\Console\Command\Command->run() at /app/vendor/symfony/console/Application.php:946
 Symfony\Component\Console\Application->doRunCommand() at /app/vendor/symfony/console/Application.php:248
 Symfony\Component\Console\Application->doRun() at /app/vendor/behat/behat/src/Behat/Testwork/Cli/Application.php:124
 Behat\Testwork\Cli\Application->doRun() at /app/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /app/vendor/behat/behat/bin/behat:34
```

There might be a misuse of the `QuestionHelper` here: the default for a choice should be a key, not a value it seems.

If that's correct, then the root of the issue is probably here: https://github.com/Behat/Behat/blob/9e065c4836a6c4787a3e9cdfd7827670c82bd6ca/src/Behat/Behat/Context/Cli/InteractiveContextIdentifier.php#L73

That would be quite weird, because this piece of code is already 2 years old.

### PR DESCRIPTION
**Pull request by greg0ire**
This is how the QuestionHelper API was intended to be used, but it only
has been so since a recent bugfix.
See symfony/symfony#25521
Fixes #1151

### CODE REVIEW

File: src/Behat/Behat/Context/Cli/InteractiveContextIdentifier.php [hunk 1]
```diff
@@ -70,7 +70,7 @@ public function guessTargetContextClass(ContextEnvironment $environment)
 
         $message = $this->translator->trans('snippet_context_choice', array('%1%' => $suiteName), 'output');
         $choices = array_values(array_merge(array('None'), $contextClasses));
-        $default = current($contextClasses);
+        $default = key($contextClasses);
```
Comment (jakzal) [inline src/Behat/Behat/Context/Cli/InteractiveContextIdentifier.php]: This is probably not what we want here. It will always return `0` and point to `None`. This should potentially be a hard coded `1` as we already check if there's at least one context class above.

**Comment by greg0ire** [comment]
@jakzal please review again

File: composer.json [hunk 2]
```diff
@@ -18,7 +18,7 @@
         "ext-mbstring": "*",
         "behat/gherkin": "^4.5.1",
         "behat/transliterator": "^1.2",
-        "symfony/console": "~2.5||~3.0||~4.0",
+        "symfony/console": "^2.7.40||^3.3.15||^4.0.3",
```
Comment (jakzal) [inline composer.json]: If it's desired to restrict the component to versions without this bug we should probably also add`^2.8.33` and `^3.4.3`.

Comment (greg0ire) [reply composer.json]: Let's revert to `~` then

Comment (greg0ire) [reply composer.json]: For 2.7 and 3.3 I mean

File: src/Behat/Behat/Context/Cli/InteractiveContextIdentifier.php [hunk 3]
```diff
@@ -70,7 +70,7 @@ public function guessTargetContextClass(ContextEnvironment $environment)
 
         $message = $this->translator->trans('snippet_context_choice', array('%1%' => $suiteName), 'output');
         $choices = array_values(array_merge(array('None'), $contextClasses));
-        $default = current($contextClasses);
+        $default = 1;
```
Comment (stof) [inline src/Behat/Behat/Context/Cli/InteractiveContextIdentifier.php]: that's weird to me. The first choice is 0, not 1

File: composer.json [hunk 4]
```diff
@@ -18,7 +18,7 @@
         "ext-mbstring": "*",
         "behat/gherkin": "^4.5.1",
         "behat/transliterator": "^1.2",
-        "symfony/console": "~2.5||~3.0||~4.0",
+        "symfony/console": "~2.7.40||^2.8.33||~3.3.15||^3.4.3||^4.0.3",
```
Comment (stof) [inline composer.json]: as this bumps the min version to 2.7+, you could also clean `InteractiveContextIdentifier::interactionIsNotSupported`

File: src/Behat/Behat/Context/Cli/InteractiveContextIdentifier.php (hunk 3 above)
Comment (jakzal) [reply src/Behat/Behat/Context/Cli/InteractiveContextIdentifier.php]: It used to select the first context class from `$contextClasses`, which is the second element of `$choices`. The first choice is `None`, and that's not the default we want.

File: composer.json (hunk 4 above)
Comment (ciaranmcnulty) [reply composer.json]: We should probably discuss whether it's ok to drop 2.5 and 2.6

Comment (greg0ire) [reply composer.json]: I might do a separate PR to do this cleanup and more.

Comment (greg0ire) [reply composer.json]: @ciaranmcnulty didn't see your message, but I think this is kind of a no-brainer, isn't it?

Comment (ciaranmcnulty) [reply composer.json]: There's no explicit BC policy in place; I think @everzet's opinion matters here

Comment (greg0ire) [reply composer.json]: I think a sensible policy might be to forbid dropping minor versions of sf unless they are no longer supported.

Comment (stof) [reply composer.json]: 2.5 and 2.6 are EOLed since years. So that's fine here.
